[graph]
all-features = true
targets = [{ triple = "x86_64-pc-windows-msvc" }, { triple = "x86_64-unknown-linux-gnu" }, { triple = "x86_64-unknown-linux-musl" }]

[advisories]
# azure-core uses `paste`
ignore = ["RUSTSEC-2024-0436"]
version = 2
yanked = "deny"

[bans]
multiple-versions = "allow"

[licenses]
allow = ["Apache-2.0", "BSL-1.0", "MIT", "Unicode-3.0"]
version = 2

[licenses.private]
ignore = true
